# Generated by Django 3.0.7 on 2020-06-10 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20200610_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='board',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.Boards'),
        ),
    ]
